# Form implementation generated from reading ui file 'breed.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import sys

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QRunnable, pyqtSlot, QThreadPool

import multiprocessing
import time

from thread_workers import WorkerSignal

breed_process = None
window = None
is_run = False
uis = {}

log_data = ""


def open_ui(ui_name):
    global window, uis
    for p in multiprocessing.active_children():
        p.terminate()
    uis[ui_name].setupUi(window, uis)


class CheckProcess(QRunnable):
    signal = WorkerSignal()

    @pyqtSlot()
    def run(self):
        global breed_process, is_run
        while breed_process.is_alive() and is_run:
            self.signal.update_log.emit()
            time.sleep(0.1)
        if is_run:
            self.signal.finished.emit()


class Ui_BreedUI(object):
    def setupUi(self, BreedUI, dict):
        global window, uis
        window = BreedUI
        uis = dict
        font = QtGui.QFont()
        font.setPointSize(16)
        BreedUI.setFont(font)
        BreedUI.setStyleSheet("*{\n"
                              "    border: none;\n"
                              "    background-color: transparent;\n"
                              "    background: none;\n"
                              "    padding: 0;\n"
                              "    margin: 0;\n"
                              "    color: #fff;\n"
                              "}\n"
                              "#centralwidget{\n"
                              "    background-color: #1f232a;\n"
                              "}\n"
                              "#featurecontainer{\n"
                              "    background-color: #16191d;\n"
                              "}\n"
                              "#MainContainer{\n"
                              "    background-color: #16191d;\n"
                              "}")
        self.centralwidget = QtWidgets.QWidget(parent=BreedUI)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.featurecontainer = QtWidgets.QWidget(parent=self.centralwidget)
        self.featurecontainer.setObjectName("featurecontainer")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.featurecontainer)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.configsubcontainer = QtWidgets.QWidget(parent=self.featurecontainer)
        self.configsubcontainer.setStyleSheet("QPushButton{\n"
                                              "    padding: 2px, 5px;\n"
                                              "}")
        self.configsubcontainer.setObjectName("configsubcontainer")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.configsubcontainer)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.homeBtn = QtWidgets.QPushButton(parent=self.configsubcontainer)
        self.homeBtn.setText("")
        self.homeBtn.setIcon(QtGui.QIcon('feather/home.svg'))
        self.homeBtn.setIconSize(QtCore.QSize(30, 30))
        self.homeBtn.setObjectName("homeBtn")
        self.verticalLayout_4.addWidget(self.homeBtn)
        self.settingsBtn = QtWidgets.QPushButton(parent=self.configsubcontainer)
        self.settingsBtn.setText("")
        self.settingsBtn.setIcon(QtGui.QIcon('feather/settings.svg'))
        self.settingsBtn.setIconSize(QtCore.QSize(30, 30))
        self.settingsBtn.setObjectName("settingsBtn")
        self.verticalLayout_4.addWidget(self.settingsBtn)
        self.verticalLayout.addWidget(self.configsubcontainer, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.scriptscontainer = QtWidgets.QWidget(parent=self.featurecontainer)
        self.scriptscontainer.setStyleSheet("QPushButton{\n"
                                            "    text-align: left;\n"
                                            "    font-size: 18px;\n"
                                            "    padding: 2px, 5px;\n"
                                            "}")
        self.scriptscontainer.setObjectName("scriptscontainer")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scriptscontainer)
        self.verticalLayout_3.setContentsMargins(5, 0, -1, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.breedBtn = QtWidgets.QPushButton(parent=self.scriptscontainer)
        self.breedBtn.setObjectName("breedBtn")
        self.breedBtn.setText("Breed")
        self.verticalLayout_3.addWidget(self.breedBtn)
        self.itemBtn = QtWidgets.QPushButton(parent=self.scriptscontainer)
        self.itemBtn.setObjectName("itemBtn")
        self.verticalLayout_3.addWidget(self.itemBtn)
        self.levelBtn = QtWidgets.QPushButton(parent=self.scriptscontainer)
        self.levelBtn.setObjectName("levelBtn")
        self.verticalLayout_3.addWidget(self.levelBtn)
        self.plantingBtn = QtWidgets.QPushButton(parent=self.scriptscontainer)
        self.plantingBtn.setObjectName("plantingBtn")
        self.verticalLayout_3.addWidget(self.plantingBtn)
        self.pokemonBtn = QtWidgets.QPushButton(parent=self.scriptscontainer)
        self.pokemonBtn.setObjectName("pokemonBtn")
        self.verticalLayout_3.addWidget(self.pokemonBtn)
        self.verticalLayout.addWidget(self.scriptscontainer)
        self.horizontalLayout.addWidget(self.featurecontainer, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.MainContainer = QtWidgets.QWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainContainer.sizePolicy().hasHeightForWidth())
        self.MainContainer.setSizePolicy(sizePolicy)
        self.MainContainer.setObjectName("MainContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.MainContainer)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.MainSubContainer = QtWidgets.QWidget(parent=self.MainContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.MainSubContainer.sizePolicy().hasHeightForWidth())
        self.MainSubContainer.setSizePolicy(sizePolicy)
        self.MainSubContainer.setObjectName("MainSubContainer")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.MainSubContainer)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.breedcontainer = QtWidgets.QWidget(parent=self.MainSubContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.breedcontainer.sizePolicy().hasHeightForWidth())
        self.breedcontainer.setSizePolicy(sizePolicy)
        self.breedcontainer.setObjectName("breedcontainer")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.breedcontainer)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.containertitlecombo = QtWidgets.QWidget(parent=self.breedcontainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.containertitlecombo.sizePolicy().hasHeightForWidth())
        self.containertitlecombo.setSizePolicy(sizePolicy)
        self.containertitlecombo.setObjectName("containertitlecombo")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.containertitlecombo)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.breedtitle = QtWidgets.QLabel(parent=self.containertitlecombo)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.breedtitle.setFont(font)
        self.breedtitle.setObjectName("breedtitle")
        self.verticalLayout_7.addWidget(self.breedtitle)
        self.verticalLayout_6.addWidget(self.containertitlecombo, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.subconfigitem = QtWidgets.QWidget(parent=self.breedcontainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.subconfigitem.sizePolicy().hasHeightForWidth())
        self.subconfigitem.setSizePolicy(sizePolicy)
        self.subconfigitem.setObjectName("subconfigitem")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.subconfigitem)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.breedcombo = QtWidgets.QComboBox(parent=self.subconfigitem)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.breedcombo.sizePolicy().hasHeightForWidth())
        self.breedcombo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.breedcombo.setFont(font)
        self.breedcombo.setStyleSheet("background-color: #1f232a; color: white;")
        self.breedcombo.setObjectName("breedcombo")
        items = ["--", "Eevee"]
        for i in range(len(items)):
            self.breedcombo.addItem(items[i])
        self.breedcombo.setMinimumContentsLength(len(max(items, key=len)))
        self.verticalLayout_8.addWidget(self.breedcombo, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_6.addWidget(self.subconfigitem, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.buttonscontainer = QtWidgets.QWidget(parent=self.breedcontainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.buttonscontainer.sizePolicy().hasHeightForWidth())
        self.buttonscontainer.setSizePolicy(sizePolicy)
        self.buttonscontainer.setStyleSheet("QPushButton{\n"
                                            "    font-size: 18px;\n"
                                            "    padding: 2px, 5px;\n"
                                            "}")
        self.buttonscontainer.setObjectName("buttonscontainer")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.buttonscontainer)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.runBtn = QtWidgets.QPushButton(parent=self.buttonscontainer)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.runBtn.setFont(font)
        self.runBtn.setStyleSheet("padding: 10px 25px 10px 25px; border: 1px solid white;")
        self.runBtn.setObjectName("runBtn")
        self.horizontalLayout_3.addWidget(self.runBtn)
        self.verticalLayout_6.addWidget(self.buttonscontainer, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_9.addWidget(self.breedcontainer)
        self.verticalLayout_2.addWidget(self.MainSubContainer)
        self.LogSubContainer = QtWidgets.QWidget(parent=self.MainContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.LogSubContainer.sizePolicy().hasHeightForWidth())
        self.LogSubContainer.setSizePolicy(sizePolicy)
        self.LogSubContainer.setObjectName("LogSubContainer")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.LogSubContainer)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.logtitle = QtWidgets.QLabel(parent=self.LogSubContainer)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.logtitle.setFont(font)
        self.logtitle.setObjectName("logtitle")
        self.verticalLayout_5.addWidget(self.logtitle, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.scrollLog = QtWidgets.QScrollArea(parent=self.LogSubContainer)
        self.scrollLog.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollLog.sizePolicy().hasHeightForWidth())
        self.scrollLog.setSizePolicy(sizePolicy)
        self.scrollLog.setStyleSheet("background-color: #2a3038;")
        self.scrollLog.setWidgetResizable(True)
        self.scrollLog.setObjectName("scrollLog")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 600, 239))
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.logLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.logLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignTop)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.logLabel.setFont(font)
        self.logLabel.setObjectName("logLabel")
        self.verticalLayout_10.addWidget(self.logLabel)
        self.scrollLog.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollLog)
        self.verticalLayout_2.addWidget(self.LogSubContainer)
        self.horizontalLayout.addWidget(self.MainContainer)
        BreedUI.setCentralWidget(self.centralwidget)

        self.threadpool = QThreadPool()

        self.homeBtn.clicked.connect(self.hide_status)
        self.homeBtn.clicked.connect(lambda: open_ui("home"))

        self.settingsBtn.clicked.connect(self.hide_status)
        self.settingsBtn.clicked.connect(lambda: open_ui("settings"))

        self.itemBtn.clicked.connect(self.hide_status)
        self.itemBtn.clicked.connect(lambda: open_ui("item"))

        self.levelBtn.clicked.connect(self.hide_status)
        self.levelBtn.clicked.connect(lambda: open_ui("level"))

        self.plantingBtn.clicked.connect(self.hide_status)
        self.plantingBtn.clicked.connect(lambda: open_ui("plant"))

        self.pokemonBtn.clicked.connect(self.hide_status)
        self.pokemonBtn.clicked.connect(lambda: open_ui("pokemon"))

        self.runBtn.clicked.connect(self.run_breed_farming)
        self.runBtn.setAutoDefault(True)

        self.retranslateUi(BreedUI)
        QtCore.QMetaObject.connectSlotsByName(BreedUI)

    def update_log(self):
        global log_data
        if os.path.isfile("log.txt"):
            with open("log.txt", "r") as f_temp:
                data_temp = f_temp.read()
            # if data has been updated
            if data_temp != log_data:
                # update it
                log_data = data_temp
                # if there is a new line at the end then strip it
                if len(log_data) != 0 and log_data[len(log_data) - 1] == "\n":
                    log_data = log_data[:-1]
                # then set the log
                self.logLabel.setText(log_data)
                self.scrollLog.verticalScrollBar().setValue(self.scrollLog.verticalScrollBar().maximum())

    def run_breed_farming(self):
        global breed_process, window, is_run
        # if everything is entered correctly
        if self.breedcombo.currentText() != "--" and not is_run:
            # delete everything from the old log
            if os.path.isfile("log.txt"):
                os.remove("log.txt")
            is_run = True
            breed_process = multiprocessing.Process(target=run_script,
                                                   args=[str(self.breedcombo.currentText())])
            breed_process.daemon = True
            breed_process.start()

            self.is_alive_worker = CheckProcess()
            # hide status once program is done
            self.is_alive_worker.signal.finished.connect(self.hide_status)
            # run update log on main thread
            self.is_alive_worker.signal.update_log.connect(self.update_log)
            self.threadpool.start(self.is_alive_worker)

            self.runBtn.setText("Stop")
        elif is_run and breed_process is not None and breed_process.is_alive():
            self.hide_status()

    def hide_status(self):
        global breed_process, is_run
        if is_run:
            is_run = False
            breed_process.terminate()
            self.runBtn.setText("Start")

    def retranslateUi(self, BreedUI):
        _translate = QtCore.QCoreApplication.translate
        BreedUI.setWindowTitle(_translate("BreedUI", "PokemonUI"))
        self.itemBtn.setText(_translate("BreedUI", "Item"))
        self.levelBtn.setText(_translate("BreedUI", "Level"))
        self.plantingBtn.setText(_translate("BreedUI", "Planting"))
        self.pokemonBtn.setText(_translate("BreedUI", "Pokemon"))
        self.breedtitle.setText(_translate("BreedUI", "Breed Farming"))
        self.breedcombo.setCurrentText(_translate("BreedUI", "--"))
        self.breedcombo.setItemText(0, _translate("BreedUI", "--"))
        self.runBtn.setText(_translate("BreedUI", "Start"))
        self.logtitle.setText(_translate("BreedUI", "Logs"))


def run_script(pokemon):
    if pokemon == "Eevee":
        # go to script folder to import main file and all dependencies
        sys.path.insert(0, "scripts/PokemonScripts/BreedFarming/EeveeBreed")
        import EeveeBreed
        EeveeBreed.run()
