# Form implementation generated from reading ui file 'PokemonUI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtWidgets, QtGui
from git import Repo
import multiprocessing
import os
import pickle

app = None

# setup app configuration and pull latest scripts

repo = Repo('scripts/PokemonScripts')
o = repo.remotes.origin
o.pull()

if os.path.isfile("window-config/window_position.dat"):
    window_position = pickle.load(open("window-config/window_position.dat", "rb"))
else:
    window_position = None

if os.path.isfile("window-config/window_size.dat"):
    window_size = pickle.load(open("window-config/window_size.dat", "rb"))
else:
    window_size = None


def closeEvent():
    global HomeWindow
    pickle.dump(HomeWindow.pos(), open("window-config/window_position.dat", "wb"))
    pickle.dump(HomeWindow.size(), open("window-config/window_size.dat", "wb"))
    for p in multiprocessing.active_children():
        p.terminate()


if __name__ == "__main__":
    import sys
    multiprocessing.freeze_support()
    app = QtWidgets.QApplication(sys.argv)
    app.setWindowIcon(QtGui.QIcon("feather/poke.ico"))
    HomeWindow = QtWidgets.QMainWindow()
    from home import Ui_HomeUI
    from settings import Ui_SettingsUI
    from item import Ui_ItemUI
    from level import Ui_LevelUI
    from plant import Ui_PlantUI
    from pokemon import Ui_PokemonUI
    from gmail import Ui_GmailUI
    from gamepath import Ui_GamePathUI
    uis = {"home": Ui_HomeUI(), "settings": Ui_SettingsUI(), "item": Ui_ItemUI(), "level": Ui_LevelUI(),
           "plant": Ui_PlantUI(), "pokemon": Ui_PokemonUI(), "gmail": Ui_GmailUI(), "gamepath": Ui_GamePathUI()}
    uis["home"].setupUi(HomeWindow, uis)
    if window_position is not None:
        HomeWindow.move(window_position)
    if window_size is not None:
        HomeWindow.resize(window_size)
    else:
        HomeWindow.resize(486, 578)
    HomeWindow.show()
    app.aboutToQuit.connect(closeEvent)
    sys.exit(app.exec())
