# Form implementation generated from reading ui file 'EverstoneFarming.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EverstoneFarming(object):
    def setupUi(self, EverstoneFarming):
        EverstoneFarming.setObjectName("MainWindow")
        EverstoneFarming.setFixedSize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=EverstoneFarming)
        self.centralwidget.setObjectName("centralwidget")
        self.sweetScentInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.sweetScentInput.setGeometry(QtCore.QRect(200, 280, 170, 22))
        self.sweetScentInput.setObjectName("sweetScentInput")
        self.sweetScentInput.setPlaceholderText("How many sweet scents")
        self.title = QtWidgets.QLabel(parent=self.centralwidget)
        self.title.setGeometry(QtCore.QRect(330, 160, 111, 41))
        self.title.setObjectName("title")
        self.title.setText("Everstone Farming")
        self.timeInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.timeInput.setGeometry(QtCore.QRect(400, 280, 170, 22))
        self.timeInput.setObjectName("timeInput")
        self.timeInput.setPlaceholderText("Duration length of script")
        self.runBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.runBtn.setGeometry(QtCore.QRect(340, 350, 93, 28))
        self.runBtn.setObjectName("runBtn")
        self.runBtn.setText("Run")
        EverstoneFarming.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=EverstoneFarming)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        EverstoneFarming.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=EverstoneFarming)
        self.statusbar.setObjectName("statusbar")
        EverstoneFarming.setStatusBar(self.statusbar)

        self.retranslateUi(EverstoneFarming)
        QtCore.QMetaObject.connectSlotsByName(EverstoneFarming)

    def retranslateUi(self, EverstoneFarming):
        _translate = QtCore.QCoreApplication.translate
        EverstoneFarming.setWindowTitle(_translate("EverstoneFarming", "EverstoneFarming"))
