# Form implementation generated from reading ui file 'gmail.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import pickle

uis = None
window_parent = None
window = None


def return_settings():
    global uis, window, window_parent
    window.hide()
    uis["settings"].setupUi(window_parent, uis)
    window_parent.show()


class Ui_GmailUI(object):

    def setupUi(self, GmailUI, ParentWindow, dict):
        global uis, window, window_parent
        window, window_parent, uis = GmailUI, ParentWindow, dict
        GmailUI.setStyleSheet("*{\n"
                              "    border: none;\n"
                              "    background-color: transparent;\n"
                              "    background: none;\n"
                              "    padding: 0;\n"
                              "    margin: 0;\n"
                              "    color: #fff;\n"
                              "}\n"
                              "#centralwidget{\n"
                              "    background-color: #1f232a;\n"
                              "}\n"
                              "#featurecontainer{\n"
                              "    background-color: #16191d;\n"
                              "}\n"
                              "#MainContainer{\n"
                              "    background-color: #16191d;\n"
                              "}")
        GmailUI.resize(ParentWindow.width() // 2, ParentWindow.height() * 2 // 3)
        GmailUI.move(ParentWindow.pos().x() + (ParentWindow.width() // 4),
                     ParentWindow.pos().y() + (ParentWindow.height() * 1 // 5))
        self.centralwidget = QtWidgets.QWidget(parent=GmailUI)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.MainContainer = QtWidgets.QWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainContainer.sizePolicy().hasHeightForWidth())
        self.MainContainer.setSizePolicy(sizePolicy)
        self.MainContainer.setObjectName("MainContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.MainContainer)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.MainSubContainer = QtWidgets.QWidget(parent=self.MainContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.MainSubContainer.sizePolicy().hasHeightForWidth())
        self.MainSubContainer.setSizePolicy(sizePolicy)
        self.MainSubContainer.setObjectName("MainSubContainer")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.MainSubContainer)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gmailcontainer = QtWidgets.QWidget(parent=self.MainSubContainer)
        self.gmailcontainer.setObjectName("gmailcontainer")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gmailcontainer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titlecontainer = QtWidgets.QWidget(parent=self.gmailcontainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.titlecontainer.sizePolicy().hasHeightForWidth())
        self.titlecontainer.setSizePolicy(sizePolicy)
        self.titlecontainer.setObjectName("titlecontainer")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.titlecontainer)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.titlegmail = QtWidgets.QLabel(parent=self.titlecontainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titlegmail.sizePolicy().hasHeightForWidth())
        self.titlegmail.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.titlegmail.setFont(font)
        self.titlegmail.setObjectName("titlegmail")
        self.verticalLayout_7.addWidget(self.titlegmail, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout.addWidget(self.titlecontainer)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.addresscontainer = QtWidgets.QWidget(parent=self.gmailcontainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addresscontainer.sizePolicy().hasHeightForWidth())
        self.addresscontainer.setSizePolicy(sizePolicy)
        self.addresscontainer.setObjectName("addresscontainer")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.addresscontainer)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.addressinput = QtWidgets.QLineEdit(parent=self.addresscontainer)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addressinput.setFont(font)
        self.addressinput.setObjectName("addressinput")
        self.addressinput.setStyleSheet("background-color: transparent; border: 1px solid white;")
        self.verticalLayout_3.addWidget(self.addressinput)
        self.verticalLayout.addWidget(self.addresscontainer)
        self.passwordcontainer = QtWidgets.QWidget(parent=self.gmailcontainer)
        self.passwordcontainer.setObjectName("passwordcontainer")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.passwordcontainer)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.passwordinput = QtWidgets.QLineEdit(parent=self.passwordcontainer)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.passwordinput.setFont(font)
        self.passwordinput.setObjectName("passwordinput")
        self.passwordinput.setStyleSheet("background-color: transparent; border: 1px solid white;")
        self.verticalLayout_4.addWidget(self.passwordinput)
        self.verticalLayout.addWidget(self.passwordcontainer)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.submitcontainergmail = QtWidgets.QWidget(parent=self.gmailcontainer)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.submitcontainergmail.setFont(font)
        self.submitcontainergmail.setObjectName("submitcontainergmail")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.submitcontainergmail)
        self.horizontalLayout_8.setObjectName("verticalLayout_8")
        self.submitBtn = QtWidgets.QPushButton(parent=self.submitcontainergmail)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.submitBtn.setFont(font)
        self.submitBtn.setStyleSheet("padding: 10px 25px 10px 25px; border: 1px solid white;")
        self.submitBtn.setObjectName("submitBtn")
        self.horizontalLayout_8.addWidget(self.submitBtn)
        self.cancelBtn = QtWidgets.QPushButton(parent=self.submitcontainergmail)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setStyleSheet("padding: 10px 25px 10px 25px; border: 1px solid white;")
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout_8.addWidget(self.cancelBtn)
        self.verticalLayout.addWidget(self.submitcontainergmail, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.horizontalLayout_2.addWidget(self.gmailcontainer)
        self.verticalLayout_2.addWidget(self.MainSubContainer)
        self.horizontalLayout.addWidget(self.MainContainer)
        GmailUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(GmailUI)
        QtCore.QMetaObject.connectSlotsByName(GmailUI)

        self.cancelBtn.clicked.connect(return_settings)
        self.submitBtn.clicked.connect(self.submit_data)

    def submit_data(self):
        if self.addressinput.text() != "" and self.passwordinput.text() != "":
            pickle.dump(self.addressinput.text(), open("email.dat", "wb"))
            pickle.dump(self.passwordinput.text(), open("mail_password.dat", "wb"))
            # then go back
            return_settings()

    def retranslateUi(self, GmailUI):
        _translate = QtCore.QCoreApplication.translate
        GmailUI.setWindowTitle(_translate("GmailUI", "PokemonUI"))
        self.titlegmail.setText(_translate("GmailUI", "Gmail Notify"))
        self.addressinput.setPlaceholderText(_translate("GmailUI", "Enter gmail address:"))
        self.passwordinput.setPlaceholderText(_translate("GmailUI", "Enter app password:"))
        self.submitBtn.setText(_translate("GmailUI", "Submit"))
        self.cancelBtn.setText(_translate("GmailUI", "Cancel"))
