# Form implementation generated from reading ui file 'item.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
import time, os
import multiprocessing
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QRunnable, pyqtSlot, QThreadPool

from thread_workers import WorkerSignal

item_process = None
window = None
is_run = False
uis = []

log_data = ""


class CheckProcess(QRunnable):
    signal = WorkerSignal()

    @pyqtSlot()
    def run(self):
        global item_process, is_run
        while item_process.is_alive() and is_run:
            self.signal.update_log.emit()
            time.sleep(0.1)
        if is_run:
            self.signal.finished.emit()


class Ui_ItemUI(object):

    def setupUi(self, ItemUI, list):
        global window, uis
        uis = list
        window = ItemUI
        ItemUI.setObjectName("MainWindow")
        font = QtGui.QFont()
        font.setPointSize(16)
        ItemUI.setFont(font)
        ItemUI.setStyleSheet("*{\n"
                             "    border: none;\n"
                             "    background-color: transparent;\n"
                             "    background: none;\n"
                             "    padding: 0;\n"
                             "    margin: 0;\n"
                             "    color: #fff;\n"
                             "}\n"
                             "#centralwidget{\n"
                             "    background-color: #1f232a;\n"
                             "}\n"
                             "#featurecontainer{\n"
                             "    background-color: #16191d;\n"
                             "}\n"
                             "#MainContainer{\n"
                             "    background-color: #16191d;\n"
                             "}")
        self.centralwidget = QtWidgets.QWidget(parent=ItemUI)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.featurecontainer = QtWidgets.QWidget(parent=self.centralwidget)
        self.featurecontainer.setObjectName("featurecontainer")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.featurecontainer)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.configsubcontainer = QtWidgets.QWidget(parent=self.featurecontainer)
        self.configsubcontainer.setStyleSheet("QPushButton{\n"
                                              "    padding: 2px, 5px;\n"
                                              "}")
        self.configsubcontainer.setObjectName("configsubcontainer")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.configsubcontainer)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.homeBtn = QtWidgets.QPushButton(parent=self.configsubcontainer)
        self.homeBtn.setText("")
        self.homeBtn.setIcon(QtGui.QIcon('feather/home.svg'))
        self.homeBtn.setIconSize(QtCore.QSize(30, 30))
        self.homeBtn.setObjectName("homeBtn")
        self.verticalLayout_4.addWidget(self.homeBtn)
        self.settingsBtn = QtWidgets.QPushButton(parent=self.configsubcontainer)
        self.settingsBtn.setText("")
        self.settingsBtn.setIcon(QtGui.QIcon('feather/settings.svg'))
        self.settingsBtn.setIconSize(QtCore.QSize(30, 30))
        self.settingsBtn.setObjectName("settingsBtn")
        self.verticalLayout_4.addWidget(self.settingsBtn)
        self.verticalLayout.addWidget(self.configsubcontainer, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.scriptscontainer = QtWidgets.QWidget(parent=self.featurecontainer)
        self.scriptscontainer.setStyleSheet("QPushButton{\n"
                                            "    text-align: left;\n"
                                            "    font-size: 18px;\n"
                                            "    padding: 2px, 5px;\n"
                                            "}")
        self.scriptscontainer.setObjectName("scriptscontainer")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scriptscontainer)
        self.verticalLayout_3.setContentsMargins(5, 0, -1, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.itemBtn = QtWidgets.QPushButton(parent=self.scriptscontainer)
        self.itemBtn.setObjectName("itemBtn")
        self.verticalLayout_3.addWidget(self.itemBtn)
        self.levelBtn = QtWidgets.QPushButton(parent=self.scriptscontainer)
        self.levelBtn.setObjectName("levelBtn")
        self.verticalLayout_3.addWidget(self.levelBtn)
        self.plantingBtn = QtWidgets.QPushButton(parent=self.scriptscontainer)
        self.plantingBtn.setObjectName("plantingBtn")
        self.verticalLayout_3.addWidget(self.plantingBtn)
        self.pokemonBtn = QtWidgets.QPushButton(parent=self.scriptscontainer)
        self.pokemonBtn.setObjectName("pokemonBtn")
        self.verticalLayout_3.addWidget(self.pokemonBtn)
        self.verticalLayout.addWidget(self.scriptscontainer)
        self.horizontalLayout.addWidget(self.featurecontainer, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.MainContainer = QtWidgets.QWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainContainer.sizePolicy().hasHeightForWidth())
        self.MainContainer.setSizePolicy(sizePolicy)
        self.MainContainer.setObjectName("MainContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.MainContainer)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.MainSubContainer = QtWidgets.QWidget(parent=self.MainContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.MainSubContainer.sizePolicy().hasHeightForWidth())
        self.MainSubContainer.setSizePolicy(sizePolicy)
        self.MainSubContainer.setObjectName("MainSubContainer")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.MainSubContainer)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.itemcontainer = QtWidgets.QWidget(parent=self.MainSubContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemcontainer.sizePolicy().hasHeightForWidth())
        self.itemcontainer.setSizePolicy(sizePolicy)
        self.itemcontainer.setObjectName("itemcontainer")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.itemcontainer)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.containertitlecombo = QtWidgets.QWidget(parent=self.itemcontainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.containertitlecombo.sizePolicy().hasHeightForWidth())
        self.containertitlecombo.setSizePolicy(sizePolicy)
        self.containertitlecombo.setObjectName("containertitlecombo")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.containertitlecombo)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.itemtitle = QtWidgets.QLabel(parent=self.containertitlecombo)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.itemtitle.setFont(font)
        self.itemtitle.setObjectName("itemtitle")
        self.verticalLayout_7.addWidget(self.itemtitle)
        self.verticalLayout_6.addWidget(self.containertitlecombo, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.subconfigitem = QtWidgets.QWidget(parent=self.itemcontainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.subconfigitem.sizePolicy().hasHeightForWidth())
        self.subconfigitem.setSizePolicy(sizePolicy)
        self.subconfigitem.setObjectName("subconfigitem")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.subconfigitem)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.itemcombo = QtWidgets.QComboBox(parent=self.subconfigitem)
        self.itemcombo.setGeometry(QtCore.QRect(140, -20, 239, 47))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemcombo.sizePolicy().hasHeightForWidth())
        self.itemcombo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.itemcombo.setFont(font)
        self.itemcombo.setStyleSheet("background-color: transparent; color: white; margin: 10px;")
        self.itemcombo.setPlaceholderText("")
        self.itemcombo.setObjectName("itemcombo")
        self.itemcombo.addItem("--")
        self.itemcombo.addItem("Amulet Coin")
        self.itemcombo.addItem("Everstone")
        self.verticalLayout_8.addWidget(self.itemcombo, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.inputsubconfig = QtWidgets.QWidget(parent=self.subconfigitem)
        self.inputsubconfig.setObjectName("inputsubconfig")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.inputsubconfig)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sweetscent = QtWidgets.QTextEdit(parent=self.inputsubconfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sweetscent.sizePolicy().hasHeightForWidth())
        self.sweetscent.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sweetscent.setFont(font)
        self.sweetscent.setStyleSheet("background-color: transparent;"
                                      "border: 1px solid white;")
        self.sweetscent.setObjectName("sweetscent")
        self.horizontalLayout_2.addWidget(self.sweetscent, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.time = QtWidgets.QTextEdit(parent=self.inputsubconfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time.sizePolicy().hasHeightForWidth())
        self.time.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.time.setFont(font)
        self.time.setStyleSheet("background-color: transparent;"
                                "border: 1px solid white;")
        self.time.setObjectName("time")
        self.horizontalLayout_2.addWidget(self.time, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout_8.addWidget(self.inputsubconfig, 0,
                                        QtCore.Qt.AlignmentFlag.AlignHCenter | QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout_6.addWidget(self.subconfigitem, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.buttonscontainer = QtWidgets.QWidget(parent=self.itemcontainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.buttonscontainer.sizePolicy().hasHeightForWidth())
        self.buttonscontainer.setSizePolicy(sizePolicy)
        self.buttonscontainer.setStyleSheet("QPushButton{\n"
                                            "    font-size: 18px;\n"
                                            "    padding: 2px, 5px;\n"
                                            "}")
        self.buttonscontainer.setObjectName("buttonscontainer")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.buttonscontainer)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.runBtn = QtWidgets.QPushButton(parent=self.buttonscontainer)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.runBtn.setFont(font)
        self.runBtn.setStyleSheet("padding: 10px 25px 10px 25px; border: 1px solid white;")
        self.runBtn.setObjectName("startBtn")
        self.horizontalLayout_3.addWidget(self.runBtn)
        self.verticalLayout_6.addWidget(self.buttonscontainer, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_9.addWidget(self.itemcontainer)
        self.verticalLayout_2.addWidget(self.MainSubContainer)
        self.LogSubContainer = QtWidgets.QWidget(parent=self.MainContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.LogSubContainer.sizePolicy().hasHeightForWidth())
        self.LogSubContainer.setSizePolicy(sizePolicy)
        self.LogSubContainer.setObjectName("LogSubContainer")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.LogSubContainer)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.logtitle = QtWidgets.QLabel(parent=self.LogSubContainer)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.logtitle.setFont(font)
        self.logtitle.setObjectName("logtitle")
        self.verticalLayout_5.addWidget(self.logtitle, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.scrollLog = QtWidgets.QScrollArea(parent=self.LogSubContainer)
        self.scrollLog.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        self.scrollLog.setSizePolicy(sizePolicy)
        self.scrollLog.setStyleSheet("background-color: #2a3038;")
        self.scrollLog.setWidgetResizable(True)
        self.scrollLog.setObjectName("scrollLog")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 861, 186))
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_1 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_1.setContentsMargins(1, 1, 1, 1)
        self.logLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.logLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignTop)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.logLabel.setFont(font)
        self.logLabel.setObjectName("logLabel")
        self.verticalLayout_1.addWidget(self.logLabel)
        self.scrollLog.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollLog)
        self.verticalLayout_2.addWidget(self.LogSubContainer)
        self.horizontalLayout.addWidget(self.MainContainer)
        ItemUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(ItemUI)

        self.threadpool = QThreadPool()

        self.homeBtn.clicked.connect(self.hide_status)
        self.homeBtn.clicked.connect(open_home_ui)

        self.pokemonBtn.clicked.connect(self.hide_status)
        self.pokemonBtn.clicked.connect(open_pokemon_ui)

        self.runBtn.clicked.connect(self.run_item_farming)
        self.runBtn.setAutoDefault(True)

        QtCore.QMetaObject.connectSlotsByName(ItemUI)

    def update_log(self):
        global log_data
        if os.path.isfile("log.txt"):
            with open("log.txt", "r") as f_temp:
                data_temp = f_temp.read()
            # if data has been updated
            if data_temp != log_data:
                # update it
                log_data = data_temp
                # if there is a new line at the end then strip it
                if len(log_data) != 0 and log_data[len(log_data) - 1] == "\n":
                    log_data = log_data[:-1]
                # then set the log
                self.logLabel.setText(log_data)
                self.scrollLog.verticalScrollBar().setValue(self.scrollLog.verticalScrollBar().maximum())

    def run_item_farming(self):
        global item_process, window, is_run
        # if everything is entered correctly
        if self.sweetscent.toPlainText() != "" and self.time.toPlainText() != "" and str(
                self.itemcombo.currentText()) != "--" and not is_run:
            # delete everything from the old log
            if os.path.isfile("log.txt"):
                os.remove("log.txt")
            is_run = True
            item_process = multiprocessing.Process(target=run_script,
                                                   args=[self.sweetscent.toPlainText(), self.time.toPlainText(),
                                                         str(self.itemcombo.currentText())])
            item_process.daemon = True
            item_process.start()

            self.is_alive_worker = CheckProcess()
            # hide status once program is done
            self.is_alive_worker.signal.finished.connect(self.hide_status)
            # run update log on main thread
            self.is_alive_worker.signal.update_log.connect(self.update_log)
            self.threadpool.start(self.is_alive_worker)

            self.runBtn.setText("Stop")
        elif is_run and item_process is not None and item_process.is_alive():
            self.hide_status()

    def hide_status(self):
        global item_process, is_run
        if is_run:
            is_run = False
            item_process.terminate()
            self.runBtn.setText("Start")

    def retranslateUi(self, ItemUI):
        _translate = QtCore.QCoreApplication.translate
        ItemUI.setWindowTitle(_translate("ItemUI", "PokemonUI"))
        self.itemBtn.setText(_translate("ItemUI", "Item"))
        self.levelBtn.setText(_translate("ItemUI", "Level"))
        self.plantingBtn.setText(_translate("ItemUI", "Planting"))
        self.pokemonBtn.setText(_translate("ItemUI", "Pokemon"))
        self.itemtitle.setText(_translate("ItemUI", "Item Farming"))
        self.sweetscent.setPlaceholderText(_translate("ItemUI", "How many sweet scents"))
        self.time.setPlaceholderText(_translate("ItemUI", "Duration length of script"))
        self.runBtn.setText(_translate("ItemUI", "Start"))
        self.logtitle.setText(_translate("ItemUI", "Logs"))


def open_home_ui():
    global window, uis
    for p in multiprocessing.active_children():
        p.terminate()
    uis[0].setupUi(window, uis)


def open_pokemon_ui():
    global window, uis
    for p in multiprocessing.active_children():
        p.terminate()
    uis[2].setupUi(window, uis)


def run_script(n, t, item):
    if item == "Everstone":
        sys.path.insert(0, "scripts/EverstoneFarming")
        EverstoneFarming.run(n, t)
    elif item == "Amulet Coin":
        sys.path.insert(0, "scripts/AmuletFarming")
        import AmuletFarming
        AmuletFarming.run(n, t)
