# Form implementation generated from reading ui file 'PlantorWater.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PlantorWaterWindow(object):
    def setupUi(self, PlantorWaterWindow):
        PlantorWaterWindow.setObjectName("MainWindow")
        PlantorWaterWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=PlantorWaterWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(360, 150, 81, 20))
        self.label.setObjectName("label")
        self.label.setText("PlantorWater")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(290, 380, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(220, 290, 170, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(390, 290, 170, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(400, 380, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        PlantorWaterWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=PlantorWaterWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        PlantorWaterWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=PlantorWaterWindow)
        self.statusbar.setObjectName("statusbar")
        PlantorWaterWindow.setStatusBar(self.statusbar)

        self.retranslateUi(PlantorWaterWindow)
        QtCore.QMetaObject.connectSlotsByName(PlantorWaterWindow)

    def retranslateUi(self, PlantorWaterWindow):
        _translate = QtCore.QCoreApplication.translate
        PlantorWaterWindow.setWindowTitle(_translate("PlantorWaterWindow", "PlantorWaterWindow"))
        self.label.setText(_translate("MainWindow", "PlantorWater"))
        self.pushButton.setText(_translate("MainWindow", "Start"))
        self.pushButton_2.setText(_translate("MainWindow", "Stop"))
