# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import os.path

from PyQt6 import QtCore, QtGui, QtWidgets
import multiprocessing

window = None
uis = {}


def open_home_ui():
    global window, uis
    for p in multiprocessing.active_children():
        p.terminate()
    uis["home"].setupUi(window, uis)


def open_item_ui():
    global window, uis
    for p in multiprocessing.active_children():
        p.terminate()
    uis["item"].setupUi(window, uis)


def open_level_ui():
    global window, uis
    for p in multiprocessing.active_children():
        p.terminate()
    uis["level"].setupUi(window, uis)


def open_plant_ui():
    global window, uis
    for p in multiprocessing.active_children():
        p.terminate()
    uis["plant"].setupUi(window, uis)


def open_pokemon_ui():
    global window, uis
    for p in multiprocessing.active_children():
        p.terminate()
    uis["pokemon"].setupUi(window, uis)


class Ui_SettingsUI(object):
    def setupUi(self, SettingsUI, dict):
        global window, uis
        uis = dict
        window = SettingsUI
        SettingsUI.setStyleSheet("*{\n"
                                 "    border: none;\n"
                                 "    background-color: transparent;\n"
                                 "    background: none;\n"
                                 "    padding: 0;\n"
                                 "    margin: 0;\n"
                                 "    color: #fff;\n"
                                 "}\n"
                                 "#centralwidget{\n"
                                 "    background-color: #1f232a;\n"
                                 "}\n"
                                 "#featurecontainer{\n"
                                 "    background-color: #16191d;\n"
                                 "}\n"
                                 "#MainContainer{\n"
                                 "    background-color: #16191d;\n"
                                 "}")
        self.centralwidget = QtWidgets.QWidget(parent=SettingsUI)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.featurecontainer = QtWidgets.QWidget(parent=self.centralwidget)
        self.featurecontainer.setObjectName("featurecontainer")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.featurecontainer)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.configsubcontainer = QtWidgets.QWidget(parent=self.featurecontainer)
        self.configsubcontainer.setStyleSheet("QPushButton{\n"
                                              "    padding: 2px, 5px;\n"
                                              "}")
        self.configsubcontainer.setObjectName("configsubcontainer")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.configsubcontainer)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.homeBtn = QtWidgets.QPushButton(parent=self.configsubcontainer)
        self.homeBtn.setText("")
        self.homeBtn.setIcon(QtGui.QIcon('feather/home.svg'))
        self.homeBtn.setIconSize(QtCore.QSize(30, 30))
        self.homeBtn.setObjectName("homeBtn")
        self.verticalLayout_4.addWidget(self.homeBtn)
        self.settingsBtn = QtWidgets.QPushButton(parent=self.configsubcontainer)
        self.settingsBtn.setText("")
        self.settingsBtn.setIcon(QtGui.QIcon('feather/settings.svg'))
        self.settingsBtn.setIconSize(QtCore.QSize(30, 30))
        self.settingsBtn.setObjectName("settingsBtn")
        self.verticalLayout_4.addWidget(self.settingsBtn)
        self.verticalLayout.addWidget(self.configsubcontainer, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.scriptscontainer = QtWidgets.QWidget(parent=self.featurecontainer)
        self.scriptscontainer.setStyleSheet("QPushButton{\n"
                                            "    text-align: left;\n"
                                            "    font-size: 18px;\n"
                                            "    padding: 2px, 5px;\n"
                                            "}")
        self.scriptscontainer.setObjectName("scriptscontainer")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scriptscontainer)
        self.verticalLayout_3.setContentsMargins(5, 0, -1, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.itemBtn = QtWidgets.QPushButton(parent=self.scriptscontainer)
        self.itemBtn.setObjectName("itemBtn")
        self.verticalLayout_3.addWidget(self.itemBtn)
        self.levelBtn = QtWidgets.QPushButton(parent=self.scriptscontainer)
        self.levelBtn.setObjectName("levelBtn")
        self.verticalLayout_3.addWidget(self.levelBtn)
        self.plantingBtn = QtWidgets.QPushButton(parent=self.scriptscontainer)
        self.plantingBtn.setObjectName("plantingBtn")
        self.verticalLayout_3.addWidget(self.plantingBtn)
        self.pokemonBtn = QtWidgets.QPushButton(parent=self.scriptscontainer)
        self.pokemonBtn.setObjectName("pokemonBtn")
        self.verticalLayout_3.addWidget(self.pokemonBtn)
        self.verticalLayout.addWidget(self.scriptscontainer)
        self.horizontalLayout.addWidget(self.featurecontainer, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.MainContainer = QtWidgets.QWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainContainer.sizePolicy().hasHeightForWidth())
        self.MainContainer.setSizePolicy(sizePolicy)
        self.MainContainer.setObjectName("MainContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.MainContainer)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.MainSubContainer = QtWidgets.QWidget(parent=self.MainContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.MainSubContainer.sizePolicy().hasHeightForWidth())
        self.MainSubContainer.setSizePolicy(sizePolicy)
        self.MainSubContainer.setObjectName("MainSubContainer")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.MainSubContainer)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gmailcontainer = QtWidgets.QWidget(parent=self.MainSubContainer)
        self.gmailcontainer.setObjectName("gmailcontainer")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.gmailcontainer)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.titlecontainer = QtWidgets.QWidget(parent=self.gmailcontainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.titlecontainer.sizePolicy().hasHeightForWidth())
        self.titlecontainer.setSizePolicy(sizePolicy)
        self.titlecontainer.setObjectName("titlecontainer")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.titlecontainer)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.titlegmail = QtWidgets.QLabel(parent=self.titlecontainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titlegmail.sizePolicy().hasHeightForWidth())
        self.titlegmail.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.titlegmail.setFont(font)
        self.titlegmail.setObjectName("titlegmail")
        self.verticalLayout_7.addWidget(self.titlegmail, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_6.addWidget(self.titlecontainer)
        self.submitcontainergmail = QtWidgets.QWidget(parent=self.gmailcontainer)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.submitcontainergmail.setFont(font)
        self.submitcontainergmail.setObjectName("submitcontainergmail")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.submitcontainergmail)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gmailBtn = QtWidgets.QPushButton(parent=self.submitcontainergmail)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.gmailBtn.setFont(font)
        self.gmailBtn.setStyleSheet("padding: 10px 25px 10px 25px; border: 1px solid white;")
        self.gmailBtn.setObjectName("gmailBtn")
        self.verticalLayout_8.addWidget(self.gmailBtn, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_6.addWidget(self.submitcontainergmail)
        self.horizontalLayout_2.addWidget(self.gmailcontainer)
        self.gamepathcontainer = QtWidgets.QWidget(parent=self.MainSubContainer)
        self.gamepathcontainer.setObjectName("gamepathcontainer")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.gamepathcontainer)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gamepathtitlecontainer = QtWidgets.QWidget(parent=self.gamepathcontainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.gamepathtitlecontainer.sizePolicy().hasHeightForWidth())
        self.gamepathtitlecontainer.setSizePolicy(sizePolicy)
        self.gamepathtitlecontainer.setObjectName("gamepathtitlecontainer")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.gamepathtitlecontainer)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.gampathtitle = QtWidgets.QLabel(parent=self.gamepathtitlecontainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gampathtitle.sizePolicy().hasHeightForWidth())
        self.gampathtitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.gampathtitle.setFont(font)
        self.gampathtitle.setObjectName("gampathtitle")
        self.verticalLayout_10.addWidget(self.gampathtitle)
        self.verticalLayout_9.addWidget(self.gamepathtitlecontainer, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gamepathBtnContainer = QtWidgets.QWidget(parent=self.gamepathcontainer)
        self.gamepathBtnContainer.setStyleSheet("")
        self.gamepathBtnContainer.setObjectName("gamepathBtnContainer")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.gamepathBtnContainer)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.gamepathBtn = QtWidgets.QPushButton(parent=self.gamepathBtnContainer)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.gamepathBtn.setFont(font)
        self.gamepathBtn.setStyleSheet("padding: 10px 25px 10px 25px; border: 1px solid white;")
        self.gamepathBtn.setObjectName("gamepathBtn")
        self.verticalLayout_12.addWidget(self.gamepathBtn)
        self.verticalLayout_9.addWidget(self.gamepathBtnContainer, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.horizontalLayout_2.addWidget(self.gamepathcontainer)
        self.verticalLayout_2.addWidget(self.MainSubContainer)
        self.LogSubContainer = QtWidgets.QWidget(parent=self.MainContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.LogSubContainer.sizePolicy().hasHeightForWidth())
        self.LogSubContainer.setSizePolicy(sizePolicy)
        self.LogSubContainer.setObjectName("LogSubContainer")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.LogSubContainer)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.logtitle = QtWidgets.QLabel(parent=self.LogSubContainer)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.logtitle.setFont(font)
        self.logtitle.setObjectName("logtitle")
        self.verticalLayout_5.addWidget(self.logtitle)
        self.scrollLog = QtWidgets.QScrollArea(parent=self.LogSubContainer)
        self.scrollLog.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollLog.sizePolicy().hasHeightForWidth())
        self.scrollLog.setSizePolicy(sizePolicy)
        self.scrollLog.setStyleSheet("background-color: #2a3038;")
        self.scrollLog.setWidgetResizable(True)
        self.scrollLog.setObjectName("scrollLog")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 451, 199))
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.logLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.logLabel.setText("")
        self.logLabel.setObjectName("logLabel")
        self.verticalLayout_13.addWidget(self.logLabel)
        self.scrollLog.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollLog)
        self.verticalLayout_2.addWidget(self.LogSubContainer)
        self.horizontalLayout.addWidget(self.MainContainer)
        self.gmailwindow = QtWidgets.QMainWindow()
        self.gmailwindow.hide()
        self.gamepathwindow = QtWidgets.QMainWindow()
        self.gamepathwindow.hide()
        SettingsUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(SettingsUI)
        QtCore.QMetaObject.connectSlotsByName(SettingsUI)

        # check status of buttons
        if os.path.isfile("email.dat") or os.path.isfile("mail_password.dat"):
            font = QtGui.QFont()
            font.setPointSize(11)
            self.gmailBtn.setFont(font)
            self.gmailBtn.setText("Remove")
        else:
            font = QtGui.QFont()
            font.setPointSize(14)
            self.gmailBtn.setFont(font)
            self.gmailBtn.setText("Add")

        if os.path.isfile("game_path.dat"):
            font = QtGui.QFont()
            font.setPointSize(11)
            self.gamepathBtn.setFont(font)
            self.gamepathBtn.setText("Remove")
        else:
            font = QtGui.QFont()
            font.setPointSize(14)
            self.gamepathBtn.setFont(font)
            self.gamepathBtn.setText("Add")

        self.gmailBtn.clicked.connect(self.gmail_options)
        self.gamepathBtn.clicked.connect(self.gamepath_options)
        self.homeBtn.clicked.connect(open_home_ui)
        self.itemBtn.clicked.connect(open_item_ui)
        self.levelBtn.clicked.connect(open_level_ui)
        self.plantingBtn.clicked.connect(open_plant_ui)
        self.pokemonBtn.clicked.connect(open_pokemon_ui)

    def gamepath_options(self):
        global uis, window
        if not os.path.isfile("game_path.dat") and self.gamepathwindow.isHidden():
            uis["gamepath"].setupUi(self.gamepathwindow, window, uis)
            window.hide()
            self.gamepathwindow.show()
        else:
            if os.path.isfile("game_path.dat"):
                os.remove("game_path.dat")
            font = QtGui.QFont()
            font.setPointSize(14)
            self.gamepathBtn.setFont(font)
            self.gamepathBtn.setText("Add")

    def gmail_options(self):
        global uis, window
        if not (os.path.isfile("email.dat") or os.path.isfile("mail_password.dat")) and self.gmailwindow.isHidden():
            uis["gmail"].setupUi(self.gmailwindow, window, uis)
            window.hide()
            self.gmailwindow.show()
        else:
            if os.path.isfile("email.dat"):
                os.remove("email.dat")
            if os.path.isfile("mail_password.dat"):
                os.remove("mail_password.dat")
            font = QtGui.QFont()
            font.setPointSize(14)
            self.gmailBtn.setFont(font)
            self.gmailBtn.setText("Add")

    def retranslateUi(self, SettingsUI):
        _translate = QtCore.QCoreApplication.translate
        SettingsUI.setWindowTitle(_translate("SettingsUI", "PokemonUI"))
        self.itemBtn.setText(_translate("SettingsUI", "Item"))
        self.pokemonBtn.setText(_translate("SettingsUI", "Pokemon"))
        self.levelBtn.setText(_translate("SettingsUI", "Level"))
        self.plantingBtn.setText(_translate("SettingsUI", "Planting"))
        self.titlegmail.setText(_translate("SettingsUI", "Gmail Notify"))
        self.gampathtitle.setText(_translate("SettingsUI", "Game Path"))
        self.logtitle.setText(_translate("SettingsUI", "Logs"))
